import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Link from "next/link";
import { Box, Grid, Text, VStack } from "@chakra-ui/react";

const Login = () => {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Welcome to patrono</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack justifyContent={'space-between'}>
        <Grid px={240} templateColumns={"1fr 1fr"} mt={160}>
          <Image
            className="mx-auto"
            src="/big-head.png"
            width={400}
            height={400}
            alt="logo"
          />
          <VStack justifyContent={"center"} spacing={12}>
            <Text fontSize={38} fontWeight={700} textAlign={"center"}>
              CALIDAD QUE INSPIRA
            </Text>
            {!user.isSignedIn ? (
              <SignInButton mode="modal">
                <button className="rounded bg-orange-500 px-4 py-2 font-bold text-white hover:bg-orange-700">
                  Ingresar
                </button>
              </SignInButton>
            ) : (
              <SignOutButton>
                <button className="rounded bg-red-500 px-4 py-2 font-bold text-white hover:bg-red-700">
                  Salir
                </button>
              </SignOutButton>
            )}
          </VStack>
        </Grid>
        <div className="px-16 py-24 text-center">
          <div style={{ marginBottom: "32px" }}>
            <span>
              Todos los datos proporcionados se encuentran sujetos a nuestra
              política de privacidad, puede acceder a ella{" "}
              <Link href={"/#"}>
                <u>aquí.</u>
              </Link>
            </span>
          </div>
          {/* <Image
          className="mx-auto"
          src="/legal-tech-logo.svg"
          width={120}
          height={120}
          alt="logo"
        /> */}
        </div>
      </VStack>
    </>
  );
};

export default Login;
